<a href="https://colab.research.google.com/github/ujin2021/NLP_CAMP/blob/main/day3/03_00_matrix_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EVN

In [2]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

### Element wise sum
* 행렬 두개의 모양이 같아야 합이 가능
* (m, n) + [(m, n) or (m, 1) or (1, n) or (1, 1)] = (m, n)
> 1일경우 1을 m or n개로 변경해서 덧셈 가능(wildcard같이 사용)

### Element wise multiplication
* (m, n) * [(m, n) or (m, 1) or (1, n) or (1, 1)] = (m, n)

### Matrix multiplication
* (m, n) x (n, l) = (m, l)
> 첫번째 matrix의 열과 두번째 matrix의 행의 수가 같아야 한다
* dot product

```
(a1, a2, a3, ..., an) · (b1, b2, ..., bn)(열벡터) = a1b1 + a2b2 + ... + anbn(scalar)
```



## 데이터

In [3]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

array([[ 0.8, -0.4, -0.8, -0.9],
       [-0.9, -0.3,  0.6,  0.8],
       [ 0.3, -0.3, -0.4,  0.9],
       [-0.1,  0.4,  0. ,  0.3],
       [ 0.9, -0.5, -0.8,  0. ]])

## element wise sum

In [4]:
arg = np.random.randint(-9, 10, (5, 4)) / 10 # hidden 과 같은 크기의 matrix
print(arg)
hidden + arg

[[-0.6  0.9 -0.7 -0.3]
 [ 0.  -0.1 -0.7  0.4]
 [-0.3  0.1 -0.1  0.2]
 [ 0.7 -0.8 -0.3 -0.8]
 [-0.5  0.8  0.9 -0.8]]


array([[ 0.2,  0.5, -1.5, -1.2],
       [-0.9, -0.4, -0.1,  1.2],
       [ 0. , -0.2, -0.5,  1.1],
       [ 0.6, -0.4, -0.3, -0.5],
       [ 0.4,  0.3,  0.1, -0.8]])

In [5]:
arg = np.random.randint(-9, 10, (1, 4)) / 10 # (1, n) 1은 wildcard처럼 작용(마치 m개가 있는 것 처럼)
print(arg)
hidden + arg

[[ 0.9 -0.6  0.6  0.5]]


array([[ 1.7, -1. , -0.2, -0.4],
       [ 0. , -0.9,  1.2,  1.3],
       [ 1.2, -0.9,  0.2,  1.4],
       [ 0.8, -0.2,  0.6,  0.8],
       [ 1.8, -1.1, -0.2,  0.5]])

In [6]:
arg = np.random.randint(-9, 10, (5, 1)) / 10 # (n, 1)
print(arg)
hidden + arg

[[ 0.9]
 [-0.5]
 [-0.2]
 [-0.1]
 [-0.9]]


array([[ 1.7,  0.5,  0.1,  0. ],
       [-1.4, -0.8,  0.1,  0.3],
       [ 0.1, -0.5, -0.6,  0.7],
       [-0.2,  0.3, -0.1,  0.2],
       [ 0. , -1.4, -1.7, -0.9]])

In [7]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
print(arg)
hidden + arg

[[-0.4]]


array([[ 0.4, -0.8, -1.2, -1.3],
       [-1.3, -0.7,  0.2,  0.4],
       [-0.1, -0.7, -0.8,  0.5],
       [-0.5,  0. , -0.4, -0.1],
       [ 0.5, -0.9, -1.2, -0.4]])

In [8]:
hidden + 1 # 모든원소에 1이 더해진다

array([[1.8, 0.6, 0.2, 0.1],
       [0.1, 0.7, 1.6, 1.8],
       [1.3, 0.7, 0.6, 1.9],
       [0.9, 1.4, 1. , 1.3],
       [1.9, 0.5, 0.2, 1. ]])

In [9]:
1 + hidden # 위와 같은 결과

array([[1.8, 0.6, 0.2, 0.1],
       [0.1, 0.7, 1.6, 1.8],
       [1.3, 0.7, 0.6, 1.9],
       [0.9, 1.4, 1. , 1.3],
       [1.9, 0.5, 0.2, 1. ]])

## element wise multiplication

In [11]:
arg = np.random.randint(-9, 10, (5, 4)) / 10 
print(arg)
hidden * arg

[[ 0.3  0.8 -0.3 -0.8]
 [ 0.1  0.2 -0.5  0.7]
 [ 0.9  0.1  0.6  0.5]
 [ 0.3 -0.7  0.4 -0.6]
 [ 0.8  0.5  0.8  0.5]]


array([[ 0.24, -0.32,  0.24,  0.72],
       [-0.09, -0.06, -0.3 ,  0.56],
       [ 0.27, -0.03, -0.24,  0.45],
       [-0.03, -0.28,  0.  , -0.18],
       [ 0.72, -0.25, -0.64,  0.  ]])

In [12]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
print(arg)
hidden * arg

[[ 0.7 -0.3  0.1  0.6]]


array([[ 0.56,  0.12, -0.08, -0.54],
       [-0.63,  0.09,  0.06,  0.48],
       [ 0.21,  0.09, -0.04,  0.54],
       [-0.07, -0.12,  0.  ,  0.18],
       [ 0.63,  0.15, -0.08,  0.  ]])

In [13]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
print(arg)
hidden * arg

[[-0.2]
 [ 0.1]
 [-0.5]
 [-0.9]
 [ 0.6]]


array([[-0.16,  0.08,  0.16,  0.18],
       [-0.09, -0.03,  0.06,  0.08],
       [-0.15,  0.15,  0.2 , -0.45],
       [ 0.09, -0.36, -0.  , -0.27],
       [ 0.54, -0.3 , -0.48,  0.  ]])

In [14]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
print(arg)
hidden * arg

[[-0.5]]


array([[-0.4 ,  0.2 ,  0.4 ,  0.45],
       [ 0.45,  0.15, -0.3 , -0.4 ],
       [-0.15,  0.15,  0.2 , -0.45],
       [ 0.05, -0.2 , -0.  , -0.15],
       [-0.45,  0.25,  0.4 , -0.  ]])

In [15]:
hidden * 2

array([[ 1.6, -0.8, -1.6, -1.8],
       [-1.8, -0.6,  1.2,  1.6],
       [ 0.6, -0.6, -0.8,  1.8],
       [-0.2,  0.8,  0. ,  0.6],
       [ 1.8, -1. , -1.6,  0. ]])

In [16]:
2 * hidden

array([[ 1.6, -0.8, -1.6, -1.8],
       [-1.8, -0.6,  1.2,  1.6],
       [ 0.6, -0.6, -0.8,  1.8],
       [-0.2,  0.8,  0. ,  0.6],
       [ 1.8, -1. , -1.6,  0. ]])

## matrix multiplication

In [20]:
arg = np.random.randint(-9, 10, (4, 5)) / 10 # hidden : (4, 5), arg: (5, 4) 두개를 matmul 하면(5, 5)가 만들어 진다
print(arg)
np.matmul(hidden, arg)

[[-0.7 -0.9  0.9  0.  -0.6]
 [ 0.   0.3  0.6  0.   0.3]
 [ 0.2  0.6 -0.3  0.9  0.4]
 [ 0.3 -0.3  0.6 -0.2  0.3]]


array([[-0.99, -1.05,  0.18, -0.54, -1.19],
       [ 0.99,  0.84, -0.69,  0.38,  0.93],
       [-0.02, -0.87,  0.75, -0.54, -0.16],
       [ 0.16,  0.12,  0.33, -0.06,  0.27],
       [-0.79, -1.44,  0.75, -0.72, -1.01]])

In [24]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
print(hidden.shape[0], arg.shape[1])
val

5 5


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[-0.99, -1.05,  0.18, -0.54, -1.19],
       [ 0.99,  0.84, -0.69,  0.38,  0.93],
       [-0.02, -0.87,  0.75, -0.54, -0.16],
       [ 0.16,  0.12,  0.33, -0.06,  0.27],
       [-0.79, -1.44,  0.75, -0.72, -1.01]])